title: Disco dance floor
hero_image: images/banner.png
description: Create a disco dance floor with a moving mirror ball that creates cool tile effects and sounds.
meta_title: Disco dance floor
meta_description: Create a disco dance floor with a moving mirror ball that creates cool tile effects and sounds.
keywords:
- unity
- ball
- marble
- 3d
- game
version: 1
listed: true
copyedit: true
last_tested: "2023-06-13"
steps:
  - title: You will make
  - title: Build the disco floor
  - title: Roll a mirror ball
    completion:
      - engaged
  - title: Dim the lights
  - title: Add random colours and sounds
    completion:
      - internal
  - title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your project
    completion:
      - external